version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - .:/app
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8000:80"
 
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes: 
      - ./public/images/:/app/public/images/
    depends_on:
      db:
        condition: service_started
 
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345
        POSTGRES_DB: symfonybase
    ports:
      - "5433:5432"

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
